django1/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/',include("newyear.urls")),
    path('tasks/',include("tasks.urls")),
]

hello/urls.py
from django.urls import path
from . import views 
urlpatterns = [
    path("",views.index,name='index'),
    path("<str:name>",views.greet, name="greet")

]

newyear/urls.py
from django.urls import path
from  . import views

urlpatterns = [
    path("",views.index,name="index")
]

tasks/urls.py
from django.urls import path
from  . import views

app_name = "tasks"
urlpatterns = [
    path("",views.index,name="index"),
    path("add",views.add,name="add")
] 

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"hello/index.html")
def greet(request,name):
    return render(request,"hello/greet.html",{
        "name": name.capitalize()
    })

newyear/views.py
import datetime
from django.shortcuts import render

def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

tasks/views.py
from django import forms
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
# Create your views here.

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request,"tasks/index.html",{
        "tasks": request.session["tasks"]
    })
def add(request):
    
    if request.method ==  "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request,"tasks/add.html",{
                "form": form
            })
    return render(request,"tasks/add.html",{
        "form": NewTaskForm()
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
    <h2> Fuck you {{name}}</h2>
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, World</h1>
</body>
</html>

newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>is it Newyear?</title>
    <link rel="stylesheet" href="{% static 'newyear/style.css' %}">
        </head>
        <body>
            {% if newyear %}
                <h1 >yes</h1>
            {% else %}
                <h2 >no</h2>
                {% endif %}
        </body>
        </html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html"%}
{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}"  method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index'%}">View Task </a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html"%}
{% block body%}
    <h1>To do list</h1>
    <ul>
        {% for task  in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add new task</a>
{% endblock%}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
    <style>
        body{
            background-color:rgb(62, 43, 43);

        }
        ul{
            color: aliceblue;
        }
        a{
            color: red;
        }
        h1{
            color: aliceblue;
        }
        form{
            color: aliceblue;
        }
    </style>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>